## 1.soru

In [1]:
# Vektör tek satırlı bir matristir

## 2.soru

In [2]:
import numpy as np

In [3]:
liste=[i for i in range(10)]
Array=np.array(liste)
Array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 3.soru
10x10 sıfır matris

In [4]:
sıfır_matris=np.zeros((10,10), dtype='int64')
sıfır_matris

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

## 4.soru
10x10 birlerden oluşan matris

In [5]:
bir_matris=np.ones((10,10))
bir_matris

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 5.soru
10x10 dokuzlardan oluşan matris

In [6]:
dokuz_matris=np.full((10,10),9)
dokuz_matris

array([[9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

## 6.soru
5 ile 25 arasinda, 3’er 3’er atlayan tek boyutlu bir Array

In [7]:
Array=np.arange(-5,25,3)
Array                

array([-5, -2,  1,  4,  7, 10, 13, 16, 19, 22])

## 7.soru
1 ile 1 arasinda 30 adet Array

In [8]:
Array=np.linspace(-1,1,30)
Array

array([-1.        , -0.93103448, -0.86206897, -0.79310345, -0.72413793,
       -0.65517241, -0.5862069 , -0.51724138, -0.44827586, -0.37931034,
       -0.31034483, -0.24137931, -0.17241379, -0.10344828, -0.03448276,
        0.03448276,  0.10344828,  0.17241379,  0.24137931,  0.31034483,
        0.37931034,  0.44827586,  0.51724138,  0.5862069 ,  0.65517241,
        0.72413793,  0.79310345,  0.86206897,  0.93103448,  1.        ])

## 8.soru
0 ile 30 arasinda 5x6’lik bir matris

In [9]:
matris=np.arange(0,30).reshape(5,6)
matris

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## 9.soru
Kosegenleri 1 olan 10x10’luk bir matris

In [10]:
birim_matris=np.eye(10)
birim_matris

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## 10.soru

0 ile 10 arasinda 5x10’lik bir matris olusturun. (integer) ve bu matrisin;

In [11]:
matris=np.random.randint(0,10,size=(5,10))
matris

array([[0, 2, 8, 1, 9, 0, 4, 7, 2, 9],
       [6, 9, 6, 2, 5, 8, 5, 7, 1, 6],
       [1, 8, 5, 6, 9, 3, 3, 2, 3, 5],
       [8, 8, 8, 1, 3, 1, 4, 0, 3, 4],
       [1, 8, 1, 3, 4, 7, 9, 7, 8, 6]])

In [12]:
# a. eleman sayisini
matris.size

50

In [13]:
# b. boyut bilgisini/sayisini
matris.ndim

2

In [14]:
# c. satir X sutun bilgisini
matris.shape

(5, 10)

In [15]:
# d. veri tipi
matris.dtype

dtype('int32')

## 11.soru
0 ile 10 arasindaki degerlerden olusan 3 adet 4x7’lik bir matris

In [16]:
np.random.randint(0,10, size=(3,4,7))

array([[[4, 7, 3, 6, 7, 7, 3],
        [2, 6, 2, 2, 9, 7, 3],
        [1, 7, 7, 4, 3, 3, 7],
        [5, 1, 0, 5, 4, 0, 8]],

       [[2, 9, 8, 8, 4, 2, 5],
        [6, 9, 6, 4, 9, 6, 3],
        [2, 4, 1, 2, 9, 4, 6],
        [5, 8, 0, 0, 7, 3, 3]],

       [[7, 4, 9, 0, 8, 4, 7],
        [4, 7, 0, 7, 3, 8, 3],
        [4, 6, 3, 4, 4, 4, 1],
        [3, 5, 3, 8, 8, 4, 3]]])

## 12.soru
Bir vektor olusturunuz ve daha sonrasinda ayni vektoru bir matrise ceviriniz

In [17]:
vektor=np.arange(0,12)
matris=vektor.reshape(4,3)
matris

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## 13.soru
4 tane ayri tek boyutlu array’i birlestirerek bir array olusturunuz

In [18]:
a=np.arange(3,6)
b=np.arange(1,8)
c=np.arange(-2,4)
d=np.arange(-7,-3)
np.concatenate([a,b,c,d])

array([ 3,  4,  5,  1,  2,  3,  4,  5,  6,  7, -2, -1,  0,  1,  2,  3, -7,
       -6, -5, -4])

## 14.soru
2 boyutlu bir vektor ve bir matris olusturun(ayri ayri), bu iki arrayi numpy metodlarini kullanarak sutun bazli birlestiriniz,

In [19]:
vektor=np.arange(1,5)
matris=np.arange(5,17).reshape(3,4)
np.vstack([vektor,matris])

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 15.soru
Numpy’da “axis=1” ve “axis=0” arasinda ne fark vardir. Teorik olarak yaziniz?

### axis=1 satır(x-ekseni), axis=0 sütunları(y-ekseni) ifade eder

## 16.soru
Farkli boyutlardaki arraylari satır ve sutun bazli ayri ayri birlestiriniz

In [20]:
a=np.random.randint(1,6,size=(3,4))
b=np.random.randint(1,6,size=(3,5))
c=np.random.randint(1,6,size=(4,4))

In [21]:
np.vstack([a,c])

array([[5, 3, 1, 4],
       [1, 3, 2, 3],
       [3, 4, 2, 2],
       [1, 4, 4, 1],
       [5, 4, 5, 2],
       [2, 4, 4, 1],
       [1, 4, 2, 1]])

In [22]:
np.hstack([a,b])

array([[5, 3, 1, 4, 2, 2, 3, 3, 5],
       [1, 3, 2, 3, 5, 1, 5, 4, 1],
       [3, 4, 2, 2, 2, 2, 5, 3, 1]])

## 17.soru
10 elemanli bi liste olusturunuz ve bu listeyi Numpy metodlariyla bolerek(split) 4 ayri array olusturunuz.

In [23]:
liste=[i for i in range(10)]
a,b,c,d=np.split(liste,[3,5,7])
print(a,b,c,d)

[0 1 2] [3 4] [5 6] [7 8 9]


## 18.soru
Random bir array olusturunuz ve bu arrayi buyukten kucuge dogru siralayiniz.Ve bu siralamadan sonra hangi elemanin hangi indexte oldugunu gosteren bir metod uygulayiniz.

In [24]:
a=np.random.randint(-7,25,7)
a

array([ 7, 10,  5, -7, 17, 20, 22])

In [25]:
np.sort(a)

array([-7,  5,  7, 10, 17, 20, 22])

In [26]:
np.argsort(a)

array([3, 2, 0, 1, 4, 5, 6], dtype=int64)

## 19.soru
20 elemanli random bir vektor olusturunuz. Bu vektorun 3. 5. ve 7. elemanlarina ulasin.

In [27]:
vektor=np.random.randint(-20,20,20)
vektor

array([-18,   7, -12,  -7,  17, -18, -10,   8,   0,  19, -13,  10, -20,
         7, -16,  -2,  11,  -7,  13,   4])

In [28]:
print(vektor[2],vektor[4],vektor[6])

-12 17 -10


## 20.soru
10 elemanli random bir vektor olusturunuz ve bu arrayin 4. elemanini farkli bir sayiyla degistiriniz.

In [29]:
vektor=np.random.randint(-5,15,10)
vektor

array([ 5,  4,  1, 12, -1, 14, -1, -4,  2, -2])

In [30]:
vektor[3]=99
vektor

array([ 5,  4,  1, 99, -1, 14, -1, -4,  2, -2])

## 21.soru
“Diagonal Matrix” ve “Trace Matrix” kavramlari hakkinda kucuk bir arastirma yapip bunlarin ne oldugunu belirten kucuk bir aciklama yaziniz.

### Bir matrisin asal köşegen üzerinde olmayan elemanları sıfır ise bu matrise diagonal matris denir.  Bir matrisin asal köşegen üzerindeki elemanları toplamına o matrisin izi (Trace of matris) denir. 

## 22.soru
5x5’lik Diagonal bir matris olusturunuz ve Diagonaline denk gelen indexlere ulasiniz.

In [43]:
diagonal=3*np.eye(5)
diagonal

array([[3., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 3., 0.],
       [0., 0., 0., 0., 3.]])

In [46]:
for i in range(5):
    print(diagonal[i,i])

3.0
3.0
3.0
3.0
3.0


## 23.soru
10 ile 20 arasinda bir vektor olusturunuz. Ve 3. indexten son indexe kadar olan degerleri yazdiriniz.

In [48]:
vektor=np.arange(10,20)
vektor

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [50]:
vektor[3:]

array([13, 14, 15, 16, 17, 18, 19])

## 24.soru
10X10 luk bir matris olusturunuz


In [53]:
matris=np.random.randint(-23,78,100).reshape(10,10)
matris

array([[ 14,   1,  42,  24,  65,  -2,   3,  64, -20,  30],
       [ 69,  12, -13, -16,   3,  31, -15,  71,  16,  -5],
       [ 14,  12,  65,  25,  15,  65, -22,  54,  76,  26],
       [ 15,  59,  27,   3, -12, -12,  -6,  31,  66,  51],
       [  1,  33,  -5,  16,  34,  28,  56,  23,   1, -11],
       [  8,  24, -10,  73,  14,  53,  41,  75, -19,  36],
       [ 52,   0,  33,  77,  24,  47,  61,  14,  -8,  23],
       [-19,  76,  76,  51,  21,  -7,  15,  52, -10, -15],
       [ 59,  38,  -6, -16,  46,  53,   9,  47,   9, -22],
       [ 76,  49,   6,  13,  -5,  30,  47,  44,   2,  13]])

3.satir ve 5.sutuna ulasiniz.

In [55]:
matris[2,4]

15

a. 5.sutunun tum satirlarina ulasiniz.

In [71]:
matris[:,4]

array([ 65,   3,  15, -12,  34,  14,  24,  21,  46,  -5])

b. Tum sutunlarin 2.satirlarina ulasiniz.

In [69]:
matris[1]

array([ 69,  12, -13, -16,   3,  31, -15,  71,  16,  -5])

c. tum sutunlarin 2 ile 7 arasindaki satirlarina ulasiniz.

In [72]:
matris[1:7]

array([[ 69,  12, -13, -16,   3,  31, -15,  71,  16,  -5],
       [ 14,  12,  65,  25,  15,  65, -22,  54,  76,  26],
       [ 15,  59,  27,   3, -12, -12,  -6,  31,  66,  51],
       [  1,  33,  -5,  16,  34,  28,  56,  23,   1, -11],
       [  8,  24, -10,  73,  14,  53,  41,  75, -19,  36],
       [ 52,   0,  33,  77,  24,  47,  61,  14,  -8,  23]])

d. satir indexi 2’den 5’e ve sutun indexi 3 den 7’ye kadar olan degerlere ulasiniz.

In [74]:
matris[2:5,3:7]

array([[ 25,  15,  65, -22],
       [  3, -12, -12,  -6],
       [ 16,  34,  28,  56]])

e. satir indexi 5’den en sona ve sutun indexi en bastan 4’e kadar olan degerlere ulasiniz.

In [77]:
matris[5:,:4]

array([[  8,  24, -10,  73],
       [ 52,   0,  33,  77],
       [-19,  76,  76,  51],
       [ 59,  38,  -6, -16],
       [ 76,  49,   6,  13]])

f. sutun indexi sadece 3, 6,9 olan kolonlarin(sutunlarin), tum satirlarina ulasiniz.

In [81]:
matris[:,[3,6,9]]

array([[ 24,   3,  30],
       [-16, -15,  -5],
       [ 25, -22,  26],
       [  3,  -6,  51],
       [ 16,  56, -11],
       [ 73,  41,  36],
       [ 77,  61,  23],
       [ 51,  15, -15],
       [-16,   9, -22],
       [ 13,  47,  13]])

g. 5. indexli satir ve 5.indexli sutuna denk gelen degeri, dogum yilinizla degistiriniz.

In [83]:
matris[5,5]=1979
matris

array([[  14,    1,   42,   24,   65,   -2,    3,   64,  -20,   30],
       [  69,   12,  -13,  -16,    3,   31,  -15,   71,   16,   -5],
       [  14,   12,   65,   25,   15,   65,  -22,   54,   76,   26],
       [  15,   59,   27,    3,  -12,  -12,   -6,   31,   66,   51],
       [   1,   33,   -5,   16,   34,   28,   56,   23,    1,  -11],
       [   8,   24,  -10,   73,   14, 1979,   41,   75,  -19,   36],
       [  52,    0,   33,   77,   24,   47,   61,   14,   -8,   23],
       [ -19,   76,   76,   51,   21,   -7,   15,   52,  -10,  -15],
       [  59,   38,   -6,  -16,   46,   53,    9,   47,    9,  -22],
       [  76,   49,    6,   13,   -5,   30,   47,   44,    2,   13]])

## 25.soru
0’dan 50’ye kadar 5’er 5’er atlayarak giden bir array olusturunuz(tek boyutlu) 

In [85]:
vektor=np.arange(0,50,5)
vektor

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

. 20 den buyuk olan kac deger var.

In [87]:
np.sum(vektor>20)

5

a. 30’dan kucuk kac deger var

In [89]:
np.sum(vektor<30)

6

b. icerisinde 33 gecen kac deger var

In [91]:
np.sum(vektor==33)

0

c. olusturulan arrayin tum elemanlarini 5 ile carpin.

In [93]:
5*vektor

array([  0,  25,  50,  75, 100, 125, 150, 175, 200, 225])

d. olusturulan arrayin tum elemanlarinin 2 ile bolumunden kalanlari yazdiriniz.

In [96]:
vektor%2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1], dtype=int32)

## 26.soru
0 ile 1 arasinda 50 elamanli bir array olusturunuz

In [101]:
vektor=np.linspace(0,1,50)
vektor

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

. ortamasini aliniz.

In [105]:
np.mean(vektor)

0.5

a. standart sapmasini aliniz.

In [108]:
np.std(vektor)

0.2945075446869757

b. varyansini aliniz.

In [111]:
np.var(vektor)

0.086734693877551

c. median’ini aliniz.

In [113]:
np.median(vektor)

0.5

d. en kucuk degeri bulunuz.

In [115]:
np.min(vektor)

0.0

e. en buyuk degeri bulunuz.

In [117]:
np.max(vektor)

1.0

# master ödev

In [165]:
import timeit
start = timeit.default_timer()
sayac=0
while True:       
    c=np.random.random((10,10))-np.random.random((10,10))
    sayac+=1
    for i in range(10):
        if c[i,i]>0.1 or c[i,i]<-0.1:
            break        
    else:
        break
stop=timeit.default_timer()
print(f'''matris:
{c}
sayaç: {sayac}
süre: {stop-start}''')
    


matris:
[[-4.99645315e-02 -9.91723410e-02 -4.80868052e-01  2.55651222e-01
  -1.54768086e-01 -1.22039919e-01 -7.63894451e-01 -5.80366850e-01
  -1.98187615e-01 -1.32252543e-01]
 [ 1.17619627e-01 -3.01645889e-02  6.21989439e-01 -7.16149888e-01
  -2.47903831e-04  2.52996848e-01 -4.23877447e-01 -5.98342594e-01
  -4.11235229e-01 -6.78424417e-01]
 [ 6.57185532e-01 -7.48593406e-01  5.21464719e-03 -8.32117531e-03
   3.38988462e-01 -1.32700779e-01  7.77347979e-01  1.29109893e-01
   5.78771916e-01 -3.72044756e-01]
 [ 3.36593333e-01  2.53474851e-01  1.41435017e-02  5.02394540e-02
   2.14962298e-01 -3.50905292e-01  2.22561414e-01  7.49684588e-01
   1.19701565e-01  7.32488015e-01]
 [-5.65258559e-02  6.58903572e-01  2.46469735e-01  1.11627558e-01
   2.96941000e-02  1.64387900e-02 -7.30994278e-01 -2.60078387e-01
  -2.80455509e-01 -3.96048585e-01]
 [-3.62985803e-01 -4.55857827e-01 -8.95309555e-02  2.48580024e-01
  -1.42622138e-01  8.44307941e-02 -3.18297338e-01 -6.95729577e-01
  -4.80212229e-01 -8.0482